Fix dotenv_as_dict value unpacking in cli:list()
The for-loop in `dotenv.cli:list()` that iterates through
`dotenv_as_dict` is missing a call to `items()`, which causes a `too
many values to unpack` `ValueError`.

Relevant traceback call:

```
  File ".../dotenv/cli.py", line 29, in list
    for k, v in dotenv_as_dict:
ValueError: too many values to unpack (expected 2)
```

This issue started happening in version 0.6.0. The previous version,
0.5.1, is not affected.