Enable the use of Mypy 0.900+
Mypy would complain about the missing `types-mock` package, which it now
needs to perform accurate type checking and despite
`ignore_missing_imports` set to `True`:

    tests/test_ipython.py:3: error: Library stubs not installed for "mock" (or incompatible with Python 3.9)
    tests/test_ipython.py:3: note: Hint: "python3 -m pip install types-mock"
    tests/test_ipython.py:3: note: (or run "mypy --install-types" to install all missing stub packages)
    tests/test_ipython.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
    tests/test_main.py:7: error: Library stubs not installed for "mock" (or incompatible with Python 3.9)
    Found 2 errors in 2 files (checked 15 source files)